name: CI - Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint (optional)
        run: |
          python -m pip install flake8
          flake8 || true

      - name: Run tests (if any)
        run: |
          # add your tests here; placeholder:
          echo "No tests configured"
